/**
 * Demo/mock data for development mode
 * Used when Supabase is not configured
 */

import type { TestRow } from '@/types/database';

export const DEMO_TESTS: TestRow[] = [
  {
    id: 'demo-listening-1',
    title: 'IELTS Listening Practice Test #1',
    slug: 'ielts-listening-practice-1',
    description: 'Complete 4-part listening test with various question types',
    module: 'listening',
    difficulty: 'medium',
    duration_minutes: 30,
    total_questions: 40,
    status: 'published',
    access: 'free',
    attempt_limit: null,
    instructions: 'Listen carefully. The audio will play once.',
    instruction_video_url: null,
    test_type: 'academic',
    created_by: 'demo-admin-001',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    published_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'demo-reading-1',
    title: 'IELTS Reading Academic Test #1',
    slug: 'ielts-reading-academic-1',
    description: '3 passages with 40 questions - Academic',
    module: 'reading',
    difficulty: 'medium',
    duration_minutes: 60,
    total_questions: 40,
    status: 'published',
    access: 'free',
    attempt_limit: null,
    instructions: 'Read each passage carefully.',
    instruction_video_url: null,
    test_type: 'academic',
    created_by: 'demo-admin-001',
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
    published_at: '2024-01-02T00:00:00Z',
  },

  {
    id: 'demo-writing-1',
    title: 'IELTS Writing Academic Test #1',
    slug: 'ielts-writing-academic-1',
    description: 'Task 1 (Graph) + Task 2 (Essay)',
    module: 'writing',
    difficulty: 'medium',
    duration_minutes: 60,
    total_questions: 2,
    status: 'published',
    access: 'free',
    attempt_limit: null,
    instructions: 'Complete both tasks within 60 minutes.',
    instruction_video_url: null,
    test_type: 'academic',
    created_by: 'demo-admin-001',
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
    published_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'demo-speaking-1',
    title: 'IELTS Speaking Test #1',
    slug: 'ielts-speaking-1',
    description: 'Full 3-part speaking interview',
    module: 'speaking',
    difficulty: 'medium',
    duration_minutes: 14,
    total_questions: 12,
    status: 'published',
    access: 'free',
    attempt_limit: null,
    instructions: 'Record your answers clearly.',
    instruction_video_url: null,
    test_type: 'academic',
    created_by: 'demo-admin-001',
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
    published_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 'demo-full-1',
    title: 'IELTS Full Mock Test #1',
    slug: 'ielts-full-mock-1',
    description: 'Complete IELTS mock test - all 4 modules',
    module: 'full',
    difficulty: 'medium',
    duration_minutes: 170,
    total_questions: 0,
    status: 'published',
    access: 'free',
    attempt_limit: null,
    instructions: 'Complete all 4 modules in order.',
    instruction_video_url: null,
    test_type: 'academic',
    created_by: 'demo-admin-001',
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
    published_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 'demo-listening-2',
    title: 'IELTS Listening Practice Test #2',
    slug: 'ielts-listening-practice-2',
    description: 'Advanced listening test with map labelling and diagrams',
    module: 'listening',
    difficulty: 'hard',
    duration_minutes: 30,
    total_questions: 40,
    status: 'published',
    access: 'paid',
    attempt_limit: 3,
    instructions: 'Listen carefully. The audio will play once.',
    instruction_video_url: null,
    test_type: 'academic',
    created_by: 'demo-admin-001',
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2024-01-06T00:00:00Z',
    published_at: '2024-01-06T00:00:00Z',
  },
  {
    id: 'demo-reading-draft',
    title: 'Reading Test Draft',
    slug: 'reading-test-draft',
    description: 'Work in progress reading test',
    module: 'reading',
    difficulty: 'easy',
    duration_minutes: 60,
    total_questions: 40,
    status: 'draft',
    access: 'free',
    attempt_limit: null,
    instructions: null,
    instruction_video_url: null,
    test_type: 'academic',
    created_by: 'demo-admin-001',
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-10T00:00:00Z',
    published_at: null,
  },
];
